name: cf2zarr
channels:
  - conda-forge
  - nodefaults
dependencies:
  - xarray
  - netCDF4
  - dask
  - zarr==2.15.0
  - pandas
  - boto3
  - s3fs==2025.3.2
  - fsspec==2025.3.2
  - aiobotocore==2.21.1
  - rioxarray

